const fs = require('fs');
const file = 'src/app/board/[slug]/player-board.tsx';
let lines = fs.readFileSync(file, 'utf8').split('\n');

// Find the grid section by trimmed content
let gridStart = -1;
let legendStart = -1;

for (let i = 0; i < lines.length; i++) {
  const trimmed = lines[i].trim();
  if (trimmed === '{/* Grid */}' && gridStart === -1) gridStart = i;
  if (trimmed === '{/* Legend */}' && legendStart === -1) legendStart = i;
}

console.log(`Grid start: line ${gridStart + 1}, Legend start: line ${legendStart + 1}`);

if (gridStart === -1 || legendStart === -1) {
  console.error('ERROR: Could not find markers.');
  // Show nearby lines for debugging
  lines.forEach((l, i) => {
    if (l.includes('Grid') || l.includes('Legend')) console.log(`  Line ${i+1}: ${JSON.stringify(l)}`);
  });
  process.exit(1);
}

const newGrid = [
  '        {/* Grid */}',
  '        <div className="overflow-x-auto pb-4">',
  '          <div className="mx-auto w-fit">',
  '            <div',
  '              className="grid"',
  '              style={{',
  '                gridTemplateColumns: hasNumbers',
  "                  ? '24px 28px repeat(10, 28px)'",
  "                  : 'repeat(10, 28px)',",
  '                gridTemplateRows: hasNumbers',
  "                  ? 'auto 20px repeat(10, 28px)'",
  "                  : 'repeat(10, 28px)',",
  "                gap: '2px',",
  '              }}',
  '            >',
  '              {/* Team A label */}',
  '              {hasNumbers && teamCol && (',
  '                <div',
  "                  style={{ gridColumn: '3 / 13', gridRow: 1 }}",
  '                  className="flex items-center justify-center text-[10px] uppercase tracking-wider text-indigo-400 font-medium h-6"',
  '                >',
  '                  {teamCol}',
  '                </div>',
  '              )}',
  '',
  '              {/* Column numbers */}',
  '              {hasNumbers && colNumbers.map((num, i) => (',
  '                <div',
  '                  key={`col-${i}`}',
  '                  style={{ gridColumn: i + 3, gridRow: 2 }}',
  '                  className="flex items-center justify-center text-[10px] font-bold text-gray-500"',
  '                >',
  '                  {num}',
  '                </div>',
  '              ))}',
  '',
  '              {/* Team B label */}',
  '              {hasNumbers && teamRow && (',
  '                <div',
  "                  style={{ gridColumn: 1, gridRow: '3 / 13' }}",
  '                  className="flex items-center justify-center"',
  '                >',
  '                  <span',
  '                    className="text-[10px] uppercase tracking-wider text-indigo-400 font-medium whitespace-nowrap"',
  "                    style={{ writingMode: 'vertical-lr', transform: 'rotate(180deg)' }}",
  '                  >',
  '                    {teamRow}',
  '                  </span>',
  '                </div>',
  '              )}',
  '',
  '              {/* Row numbers + squares */}',
  '              {Array.from({ length: 10 }, (_, row) => {',
  '                const gridRow = hasNumbers ? row + 3 : row + 1;',
  '                const colOffset = hasNumbers ? 3 : 1;',
  '',
  '                return (',
  '                  <React.Fragment key={`row-group-${row}`}>',
  '                    {/* Row number */}',
  '                    {hasNumbers && (',
  '                      <div',
  '                        style={{ gridColumn: 2, gridRow }}',
  '                        className="flex items-center justify-center text-[10px] font-bold text-gray-500"',
  '                      >',
  '                        {rowNumbers[row]}',
  '                      </div>',
  '                    )}',
  '',
  '                    {/* Squares */}',
  '                    {Array.from({ length: 10 }, (_, col) => {',
  '                      const position = row * 10 + col;',
  '                      const sq = squares[position];',
  '                      if (!sq) return <div key={`empty-${position}`} style={{ gridColumn: col + colOffset, gridRow }} />;',
  '',
  '                      const isPaid = sq.paymentStatus === "paid";',
  '                      const isPending = sq.paymentStatus === "pending";',
  '                      const isReservedCash = sq.paymentStatus === "reserved_cash";',
  '                      const isAvailable = sq.paymentStatus === "open" && isOpen;',
  '                      const isSelected = selectedSquare?.squareId === sq.squareId;',
  '                      const isWinner = winnerSet.has(position) && isPaid;',
  '',
  '                      return (',
  '                        <button',
  '                          key={sq.squareId}',
  '                          disabled={!isAvailable}',
  '                          onClick={() => handleSquareTap(sq)}',
  '                          style={{ gridColumn: col + colOffset, gridRow }}',
  '                          className={`aspect-square rounded-md flex items-center justify-center text-[10px] font-medium transition-all ${',
  '                            isSelected',
  '                              ? "bg-indigo-600 border-2 border-indigo-400 text-white ring-2 ring-indigo-500/30"',
  '                              : isWinner',
  '                                ? "bg-yellow-500/20 border-2 border-yellow-400 text-yellow-300 ring-1 ring-yellow-400/30"',
  '                                : isPaid',
  '                                  ? "bg-green-950 border border-green-900 text-green-400"',
  '                                  : isReservedCash',
  '                                    ? "bg-amber-950 border border-amber-800 text-amber-500"',
  '                                    : isPending',
  '                                      ? "bg-yellow-950 border border-yellow-900 text-yellow-500"',
  '                                      : isAvailable',
  '                                        ? "bg-gray-900 border border-gray-800 text-gray-600 hover:border-indigo-700 hover:bg-indigo-950/30 active:scale-95 cursor-pointer"',
  '                                        : "bg-gray-900 border border-gray-800 text-gray-700"',
  '                          }`}',
  '                          title={',
  '                            isWinner',
  '                              ? `★ WINNER — ${sq.playerName ?? "Paid"}`',
  '                              : isPaid',
  '                                ? sq.playerName ?? "Paid"',
  '                                : isReservedCash',
  '                                  ? `Reserved (cash) — ${sq.playerName ?? ""}`',
  '                                  : isPending',
  '                                    ? "Pending payment"',
  '                                    : isAvailable',
  '                                      ? `Square ${position + 1} — ${priceDisplay}`',
  '                                      : "Unavailable"',
  '                          }',
  '                        >',
  '                          {isWinner',
  '                            ? "★"',
  '                            : isPaid && sq.playerName',
  '                              ? getInitials(sq.playerName)',
  '                              : isReservedCash',
  '                                ? "💵"',
  '                                : isPending',
  '                                  ? "…"',
  '                                  : <span className="text-gray-700">{position + 1}</span>}',
  '                        </button>',
  '                      );',
  '                    })}',
  '                  </React.Fragment>',
  '                );',
  '              })}',
  '            </div>',
  '          </div>',
  '        </div>',
  '',
];

lines.splice(gridStart, legendStart - gridStart, ...newGrid);
fs.writeFileSync(file, lines.join('\n'));
console.log('SUCCESS: Grid replaced with unified single-grid layout');
