-- Roster identity -- email primary, phone secondary.
--
-- identity_key is RENAMED, not duplicated. Same meaning, same values: it has
-- always held a trimmed, lowercased email. The name became ambiguous the
-- moment a second key existed, and a rename carries the data and the index
-- with it -- no backfill, no dual-write window, no legacy-key deprecation
-- step. The index is renamed alongside so nothing is left saying identity_key.
--
-- phone_key is the only genuinely new column.
--
-- UNIQUE ON BOTH. One normalized email and one normalized phone per supporter
-- within an event. Ordered lookup -- email, then phone, never OR -- then binds
-- to AT MOST ONE existing supporter, with no set to order and therefore no
-- tie-break anywhere. `email OR phone` would chain transitively: A shares an
-- email with B, B shares a phone with C, C is silently merged into A.
--
-- NULLS DO NOT BLOCK THE UNIQUE INDEX. Postgres treats them as distinct, so
-- the one legacy supporter with no phone is fine and could never collide.
-- Presence is enforced by the application, uniqueness by the index.
--
-- THE BACKFILL IS GENERATED, not hand-written:
--   node --experimental-strip-types scripts/generate-phone-backfill.mts
-- It imports the same normalizePhone the write path calls. Reimplementing
-- E.164 in PL/pgSQL would be exactly the second implementation the rule
-- forbids, and the one that drifts. Verify afterwards with --verify, which
-- re-runs the real function over the stored values and asserts a no-op.

ALTER TABLE "event_supporters" RENAME COLUMN "identity_key" TO "email_key";
ALTER INDEX "event_supporters_event_identity_key" RENAME TO "event_supporters_event_email_key";

ALTER TABLE "event_supporters" ADD COLUMN "phone_key" TEXT;

-- GENERATED by scripts/generate-phone-backfill.mts. Do not hand-edit.
-- A row that no longer exists makes its UPDATE a harmless no-op, which is what
-- lets this replay onto an empty database.
-- is what lets this replay onto an empty database.
UPDATE "event_supporters" SET "phone_key" = '+16785237571' WHERE "id" = '43e0518d-53c8-44f0-b09f-cb28de83e344';
UPDATE "event_supporters" SET "phone_key" = '+16785237571' WHERE "id" = 'ead0659d-09ad-4b70-b466-2a9e6be6a79c';
UPDATE "event_supporters" SET "phone_key" = '+16785237571' WHERE "id" = '0f66ccfe-9e69-4252-b7f7-087bc6a12b68';
UPDATE "event_supporters" SET "phone_key" = '+16785237571' WHERE "id" = '3a27494f-74a2-43a6-9154-8069adc54ff2';
UPDATE "event_supporters" SET "phone_key" = '+16785237571' WHERE "id" = '93bf76b8-e7d9-4e05-b50e-76999c765f3a';
UPDATE "event_supporters" SET "phone_key" = '+16785237571' WHERE "id" = 'a5c3d66f-a135-45a1-b563-e169e9d6052d';
UPDATE "event_supporters" SET "phone_key" = '+16017355807' WHERE "id" = '4ad44abf-058a-4703-b0f6-ebffc1009e27';
UPDATE "event_supporters" SET "phone_key" = '+16017355806' WHERE "id" = 'e4ca0bff-8946-4f1f-baf4-bf55e32fec63';
UPDATE "event_supporters" SET "phone_key" = '+16017355243' WHERE "id" = 'e3196b7b-dda1-41aa-9815-10a44ea33c4b';
-- ea612d65-5531-47cf-8011-9f23e66e4c47: no usable phone ("61085236846"), phone_key left NULL
UPDATE "event_supporters" SET "phone_key" = '+16017356988' WHERE "id" = 'ae0fa0e8-4057-40c3-80a4-b9edcded9df0';
-- 3f3d4696-1e48-4e08-aa50-04f30fb01b04: no usable phone (null), phone_key left NULL

CREATE UNIQUE INDEX "event_supporters_event_phone_key"
  ON "event_supporters" ("event_id", "phone_key");

-- GATE. Same transaction, so a failure rolls the whole thing back rather than
-- leaving a half-keyed table.
DO $$
DECLARE
  bad_shape INTEGER;
  dupes     INTEGER;
BEGIN
  -- Shape only. The authoritative no-op check runs through the real
  -- normalizer in --verify; this catches a mangled generator output.
  SELECT count(*) INTO bad_shape
    FROM event_supporters
   WHERE phone_key IS NOT NULL
     AND phone_key !~ '^\+[0-9]{8,15}$';
  IF bad_shape > 0 THEN
    RAISE EXCEPTION 'roster identity aborted: % phone_key value(s) are not E.164', bad_shape;
  END IF;

  SELECT count(*) INTO dupes FROM (
    SELECT event_id, phone_key FROM event_supporters
     WHERE phone_key IS NOT NULL
     GROUP BY event_id, phone_key HAVING count(*) > 1) d;
  IF dupes > 0 THEN
    RAISE EXCEPTION
      'roster identity aborted: % duplicate (event_id, phone_key) group(s); resolve the supporters first',
      dupes;
  END IF;
END $$;
