// Generates the phone_key backfill SQL for the roster-identity migration,
// and verifies it afterwards.
//
// WHY GENERATED AND NOT HAND-WRITTEN. The ruling is that the backfill runs
// through the same function that runs at write time, never a second
// implementation. A .sql file cannot call TypeScript, so the next best thing —
// and the thing this does — is to make the SQL an OUTPUT of the real
// normalizer rather than a transcription of what someone believed it does.
// Generator and output both ship in the PR, so the SQL can be regenerated and
// diffed against what was applied.
//
// Reimplementing E.164 in PL/pgSQL would have been the second implementation
// the ruling forbids, and the one that silently drifts.
//
//   generate:  node --experimental-strip-types scripts/generate-phone-backfill.mts
//   verify:    node --experimental-strip-types scripts/generate-phone-backfill.mts --verify
//
// Reads DIRECT_URL from the env file named by BACKFILL_ENV (default .env).
// Prints SQL to stdout. Writes nothing, and in --verify mode reads only.

import { readFileSync } from "node:fs";
import { PrismaClient } from "@prisma/client";
import { normalizePhone } from "../src/lib/roster-identity.ts";

function envVar(file: string, key: string): string {
  for (const line of readFileSync(file, "utf8").split(/\r?\n/)) {
    const m = line.match(/^([A-Z_]+)=(.*)$/);
    if (m && m[1] === key) return m[2].replace(/^["']|["']$/g, "");
  }
  throw new Error(`${key} not found in ${file}`);
}

const envFile = process.env.BACKFILL_ENV ?? ".env";
const verify = process.argv.includes("--verify");
const db = new PrismaClient({
  datasources: { db: { url: envVar(envFile, "DIRECT_URL") } },
});

const rows = await db.eventSupporter.findMany({
  select: { id: true, phone: true },
  orderBy: { createdAt: "asc" },
});

if (verify) {
  // THE NO-OP ASSERTION, run through the real function against what is
  // actually stored. Re-normalizing a backfilled value must change nothing;
  // if it does, the column and the write path disagree and every future
  // lookup is a coin flip.
  const stored = await db.eventSupporter.findMany({
    select: { id: true, phone: true, phoneKey: true },
  });
  let drift = 0;
  let missing = 0;
  for (const s of stored) {
    if (s.phoneKey === null) {
      // Legitimate only where there was no phone to normalize.
      if (normalizePhone(s.phone) !== null) {
        missing++;
        console.error(`MISSING  ${s.id}: has a usable phone, phone_key is NULL`);
      }
      continue;
    }
    if (normalizePhone(s.phoneKey) !== s.phoneKey) {
      drift++;
      console.error(`NOT IDEMPOTENT  ${s.id}: ${s.phoneKey} -> ${normalizePhone(s.phoneKey)}`);
    }
    if (normalizePhone(s.phone) !== s.phoneKey) {
      drift++;
      console.error(`DISAGREES  ${s.id}: phone normalizes to ${normalizePhone(s.phone)}, stored ${s.phoneKey}`);
    }
  }
  console.log(`checked ${stored.length} supporters | drift: ${drift} | missing: ${missing}`);
  await db.$disconnect();
  process.exit(drift + missing === 0 ? 0 : 1);
}

const lines: string[] = [];
let skipped = 0;
for (const r of rows) {
  const key = normalizePhone(r.phone);
  if (!key) {
    // No phone, or one this normalizer refuses. Left NULL rather than guessed
    // — the unique index treats NULLs as distinct, so it blocks nothing.
    skipped++;
    lines.push(`-- ${r.id}: no usable phone (${JSON.stringify(r.phone)}), phone_key left NULL`);
    continue;
  }
  lines.push(`UPDATE "event_supporters" SET "phone_key" = '${key}' WHERE "id" = '${r.id}';`);
}

console.log(`-- GENERATED by scripts/generate-phone-backfill.mts. Do not hand-edit.`);
console.log(`-- ${rows.length} supporters, ${rows.length - skipped} with a usable phone, ${skipped} left NULL.`);
console.log(`-- A row that no longer exists makes its UPDATE a harmless no-op, which`);
console.log(`-- is what lets this replay onto an empty database.`);
console.log(lines.join("\n"));

await db.$disconnect();
